# Generated by Django 5.1.5 on 2025-01-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactmemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=150)),
                ('email_model', models.EmailField(max_length=254)),
                ('contactnumber_model', models.CharField(max_length=12)),
                ('designation_model', models.CharField(max_length=100)),
                ('subject_model', models.CharField(max_length=150)),
                ('message_model', models.CharField(max_length=500)),
            ],
        ),
    ]
